Gm/validator added event test
bloxapp/ssv pull request #1124
Opened 2023-08-30 12:33 UTC by guym-blox

2023-09-05 14:15 UTC, y0sher commented on network/p2p/p2p.go
> -func New(logger *zap.Logger, cfg *Config) network.P2PNetwork {
this file should not be affected by the iface you create in `validator`.

2023-09-05 14:15 UTC, y0sher commented on network/p2p/p2p_test.go
> +func registerHandler(logger *zap.Logger, node validator.P2PNetwork, mid spectypes.MessageID, height specqbft.Height, round specqbft.Round, counter *int64, errors chan<- error) {
same comment as on other p2p files

2023-09-05 14:16 UTC, y0sher commented on network/p2p/test_utils.go
> +	Nodes    []validator.P2PNetwork
same comment as on other p2p files, this should stay `network.P2PNetwork`

2023-09-05 14:16 UTC, y0sher commented on network/p2p/test_utils.go
> +func (ln *LocalNet) NewTestP2pNetwork(ctx context.Context, keys testing.NodeKeys, logger *zap.Logger, maxPeers int) (validator.P2PNetwork, error) {
same comment as on other p2p files, this should stay `network.P2PNetwork`

2023-09-05 14:16 UTC, y0sher commented on network/p2p/test_utils.go
> +	nodes, keys, err := testing.NewLocalTestnet(ctx, n, func(pctx context.Context, keys testing.NodeKeys) validator.P2PNetwork {
same comment as on other p2p files, this should stay `network.P2PNetwork`

2023-09-05 14:16 UTC, y0sher commented on network/testing/local.go
> +	nodes := make([]validator.P2PNetwork, n)
same comment as on other p2p files, this should stay `network.P2PNetwork`

2023-09-05 14:16 UTC, y0sher commented on operator/node.go
> +	P2PNetwork          validator.P2PNetwork
same comment as on other p2p files, this should stay `network.P2PNetwork`

2023-09-05 14:16 UTC, y0sher commented on operator/node.go
> +	net              validator.P2PNetwork
same comment as on other p2p files, this should stay `network.P2PNetwork`

2023-09-05 16:04 UTC, y0sher commented on operator/validator/controller.go
> +type Metrics interface {
no need to test metrics honestly, just use noop metrics in test

2023-09-06 14:46 UTC, y0sher requested changes
Would love to test these functions - 
`onShareRemove`
`UpdateValidatorMetadata` - only half tested
`setupNonCommitteeValidators`
`UpdateValidatorMetaDataLoop` - might require some changes but testing this is crucial

2023-09-18 13:28 UTC, y0sher commented
@guym-blox just make sure lint and ut are passing so we can approve and merge

2023-10-01 15:32 UTC, y0sher approved these changes

2024-01-14 13:32 UTC, y0sher commented on operator/validator/validators_map.go
why is this here? we have validators_map package one folder above, are you moving it? because it seems that this is just duplicate with additions?

2024-01-14 13:33 UTC, y0sher commented on operator/validator/controller_test.go
> +//	func TestOnRemoveShare(t *testing.T) {
remove this if not needed

2024-01-17 13:28 UTC, y0sher commented on cli/operator/node.go
run go imports on this

2024-01-17 13:28 UTC, y0sher commented on integration/qbft/tests/scenario_test.go
run go imports

2024-01-17 13:28 UTC, y0sher commented on integration/qbft/tests/setup_test.go
run go imports

2024-01-17 13:28 UTC, y0sher commented on operator/validator/controller.go
> +	"github.com/bloxapp/ssv/protocol/v2/qbft/roundtimer"
run go imports

2024-01-17 13:29 UTC, y0sher commented on operator/validator/controller.go
> +	ReportValidation(logger *zap.Logger, message *spectypes.SSVMessage, res p2pprotocol.MsgValidationResult)
are all of these really used by validatorController or by where it passes it to. if not reduce the interface as much as possible

2024-01-17 13:29 UTC, y0sher requested changes
semantics

2024-01-21 16:01 UTC, y0sher submitted a review, later dismissed

2024-01-21 16:16 UTC, moshe-blox approved these changes

2024-01-21 16:18 UTC, moshe-blox commented
Well done, LGTM 🔥

2024-01-21 16:24 UTC, y0sher approved these changes

2024-01-21 16:25 UTC, merged