Fix: Share Removal by Validator PubKey
bloxapp/ssv pull request #1140
Opened 2023-09-10 11:07 UTC by olegshmuelov

### Problem

Previously, shares were being removed based on the validator's public key, which was incorrect.

### Solution

This fix introduces the proper way to delete a share by using the share's public key instead of the validator's public key. This ensures that the correct share is removed from the EKM (ETH Key Manager) storage.

2023-09-10 14:54 UTC, moshe-blox requested changes
Code looks good 💪

Unrelated to this fix, I think there's another bug: `RemoveShare` is called from a task and not from event handler. This means that it's not part of the DB transaction and task failures are ignored (whereas event handling failures are retried).

I think we should do this in this PR because this would make the primary fix testable in `TestHandleBlockEventsStream` (which doesn't run tasks) by adding a test that removes a validator and checks that the SP data is gone as well.

Wdyt? @y0sher @olegshmuelov

2023-09-10 15:10 UTC, y0sher commented
> Code looks good 💪
> 
> Unrelated to this fix, I think there's another bug: `RemoveShare` is called from a task and not from event handler. This means that it's not part of the DB transaction and task failures are ignored (whereas event handling failures are retried).
> 
> I think we should do this in this PR because this would make the primary fix testable in `TestHandleBlockEventsStream` (which doesn't run tasks) by adding a check on the SP data in the already existing test that removes a validator.
> 
> Wdyt? @y0sher @olegshmuelov

I strongly agree that any code that plays with database should be as part of the tx in `eventhandler`.

2023-09-11 13:26 UTC, olegshmuelov commented
### Concern: Migration for Existing Shares

While this PR fixes the issue of shares being incorrectly removed by the validator's public key, it's worth noting that there may be existing shares in the ETH Key Manager storage that were not properly deleted due to this bug.

I recommend considering the creation of a migration script that scans for and deletes these improperly removed shares, particularly those that were not deleted by the `ValidatorRemove` event. This will ensure data integrity and consistency in the ETH Key Manager storage moving forward.

@moshe-blox @y0sher

2023-09-12 09:23 UTC, y0sher submitted a review, later dismissed
@olegshmuelov I agree about the migration point, though I think even without the migration there is no hard of having old shares in your DB. so we should make it a point to release the new version with this migration but it dosen't have to be a part of this task. I can create a task for it. 
@moshe-blox wdyt?

2023-09-13 12:22 UTC, moshe-blox approved these changes

2023-09-13 12:24 UTC, y0sher approved these changes

2023-09-13 13:07 UTC, merged