fix generate operator keys command
bloxapp/ssv pull request #1142
Opened 2023-09-11 11:38 UTC by guym-blox

2023-09-12 09:13 UTC, y0sher commented on cli/generate_operator_keys.go
> +	passwordBytes, err := os.ReadFile(absPath)
generally, I would take all I/O (file reading/writing) to different function, either the top function or just separate functions. this makes a more reusable and testable code.

2023-09-12 09:13 UTC, y0sher commented on cli/generate_operator_keys.go
> +	pk, err := base64.StdEncoding.DecodeString(operatorPublicKey)
don't we already have tested methods for all this stuff in `rsaencryption`? if we do its better to reuse them instead of rewriting the code.

2023-09-12 09:14 UTC, y0sher requested changes
Generally the change works, It'll be great to make it more future-proof.

2023-09-13 11:45 UTC, y0sher commented on cli/generate_operator_keys.go
> +}
this function is weird, you don't need logger if you return errors. return the error and log at the top level instead.

2023-09-13 11:48 UTC, y0sher commented on cli/generate_operator_keys.go
> +				logger.Fatal("Failed to read private key from file", zap.Error(err))
I meant more for something like this -
```go
if privateKeyFilePath != "" {
   keybytes, err := readFile(privateKeyFilePath)
   if err != nil {
    logger.Fatal("failed to read file", zap.Error(err))
   }
  sk, err := readPrivateKey(keybytes)
  if err != nil {
    logger.Fatal("failed to parse public key", zap.Error(err))
  }
 pk = sk.PublicKey
}
  ```

2023-09-13 11:50 UTC, y0sher commented on cli/generate_operator_keys.go
> +			encryptAndSavePrivateKey(sk, passwordFilePath, logger)
please use similar structure to what I described above.
one function that encrypts and returns either encrypted data or error, and then use the writeFile func to write the returned data.

2023-09-18 07:44 UTC, y0sher approved these changes

2023-09-18 11:19 UTC, moshe-blox approved these changes

2023-09-18 11:20 UTC, merged