Refactored Monitoring guide
bloxapp/ssv pull request #1145
Opened 2023-09-19 10:21 UTC by RaekwonIII

Added simpler Grafana config files

2023-09-19 15:59 UTC, andrew-blox requested changes

2023-09-19 15:59 UTC, andrew-blox commented on monitoring/README.md
> +Make sure your node is exposing a `/metrics` and `/health` endpoints. This is done via node configuration, as explained in the [Installation guide on the docs]([../installation.md#metrics-configurati
Broken link

2023-09-19 15:59 UTC, andrew-blox commented on monitoring/README.md
>  In case the node is healthy it returns an HTTP Code `200` with empty response:
`with empty response` -> `with an empty response`

2023-09-19 15:59 UTC, andrew-blox commented on monitoring/README.md
>  In case the node is healthy it returns an HTTP Code `200` with empty response:
Below:
`with HTTP Code 500` ->  `with an HTTP Code of 500`

2023-09-19 15:59 UTC, andrew-blox commented on operator/duties/scheduler_test.go
> +
In general this PR should be related to "Refactored Monitoring guide", please next time open a separate PR for separate tasks.

2023-09-19 16:01 UTC, andrew-blox commented on operator/duties/scheduler_test.go
> +
Ah sorry missed your comment above, no prob :)

2023-09-21 13:55 UTC, RaekwonIII commented
Acted on changes requested.
Only thing now are the two "rogue" changes are harmless (can anybody confirm)...

2023-09-25 14:03 UTC, nkryuchkov reviewed
Great improvements, thanks! Just a couple of questions. Also, could you please rebase your commits onto stage? 

```
git checkout monitoring-page-refactor
git fetch
git rebase stage
git push --force-with-lease
```

Please let me know if you need any help with that

2023-09-25 14:54 UTC, nkryuchkov commented on monitoring/README.md
> +> ⚠️ Note: If you are not running Prometheus as a Docker container, but as an executable, change the \`targets\` in the config file to reflect the correct networking connections. In the case where th
@RaekwonIII thanks

2023-09-25 14:55 UTC, nkryuchkov approved these changes

2023-10-02 12:26 UTC, andrew-blox approved these changes

2023-10-31 23:12 UTC, lior-blox commented
@RaekwonIII @zktaiga 

Can we combine https://github.com/bloxapp/ssv/pull/1145
into this pr?

2023-10-31 23:16 UTC, RaekwonIII commented
I discussed it this morning with @zktaiga , we convened that he'll rebase his on top of my branch and eventually supersede this, I think.

2023-11-01 08:06 UTC, zktaiga commented
> @RaekwonIII @zktaiga
> 
> Can we combine #1145 into this pr?

See https://github.com/bloxapp/ssv/pull/1176#issuecomment-1788565093

2023-11-02 13:27 UTC, zktaiga commented
Superseded by #1176

2023-11-02 13:27 UTC, closed without merging