Don't consider same duty slashable
bloxapp/ssv pull request #1335
Opened 2024-03-05 11:00 UTC by nkryuchkov

2024-03-05 11:19 UTC, nkryuchkov commented on protocol/v2/ssv/valuechecker/sync_committee_contribution.go
> +	//contributions, _ := cd.GetSyncCommitteeContributions()
Copied from spec

2024-03-06 13:09 UTC, nkryuchkov commented on protocol/v2/ssv/valuechecker/sync_committee_contribution.go
> +	//contributions, _ := cd.GetSyncCommitteeContributions()
Outdated

2024-03-18 17:10 UTC, olegshmuelov requested changes
The current comparison in the wrapper focuses solely on epoch data (Source and Target). Given our strict [slashing protection rules](https://github.com/bloxapp/eth2-key-manager/blob/eca3b4b2f95f4ef286cc0489de9552717f5f0aba/slashing_protection/normal_protection.go#L35), it's crucial to compare the whole struct to ensure we're accurately identifying identical attestations. I suggest we expand the comparison to cover the entire attestation data structure, not just the Source and Target.

Additionally, it's important to note that when a validator is registered/reactivated, we update the attestation data without storing any signing root information. This practice could impact the effectiveness of the new changes, as the absence of signing root data might compromise our ability to accurately assess slashable conditions under the revised logic.

2024-03-19 09:09 UTC, nkryuchkov commented
After discussing this with @olegshmuelov, we came to conclusion that this approach might be too dangerous and avoiding touching slashing protection would be preferable.

Therefore, we need to consider making the "past round" check tolerant to partial signature messages from the previous round.

2024-03-19 12:28 UTC, nkryuchkov commented
I was wrong about partial signature messages in the previous comment. Actually it's decided messages. PoC PR: https://github.com/bloxapp/ssv/pull/1343

2024-03-19 17:25 UTC, nkryuchkov commented
On hold, it will likely be superseded by https://github.com/bloxapp/ssv/pull/1343

2024-04-01 14:41 UTC, closed without merging