fix: voluntary exit signature in post-deneb networks
bloxapp/ssv pull request #1338
Opened 2024-03-11 14:34 UTC by y0sher

### Issue:
Following the Deneb fork on the Ethereum Holesky network, the domain in signatures of voluntary exit messages was fixed to the Capella fork and epoch. This change was not accounted for in our codebase, leading to a critical bug where voluntary exits failed on networks post-Deneb.

### Solution:
This PR introduces a fix that aligns our handling of voluntary exit signatures with the updated domain requirements set forth by the Deneb fork. It ensures voluntary exits are correctly processed in networks operating under the post-Deneb specifications.

2024-03-11 14:49 UTC, nkryuchkov approved these changes

2024-03-11 14:49 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +) (phase0.Domain, error) {
Why do we need this to be the new line?

2024-03-11 14:49 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +	forkData.GenesisValidatorsRoot = response.Data.GenesisValidatorsRoot
It likely won't ever happen, but I'd also make sure that `response.Data != nil`

2024-03-11 15:14 UTC, nkryuchkov approved these changes

2024-03-11 20:01 UTC, zippoxer approved these changes

2024-03-12 09:48 UTC, olegshmuelov requested changes

2024-03-12 09:48 UTC, olegshmuelov commented on beacon/goclient/signing.go
> +	}
we should check for spec response is nil

2024-03-12 09:48 UTC, olegshmuelov commented on beacon/goclient/signing.go
> +	}
same here

2024-03-12 09:50 UTC, olegshmuelov commented on beacon/goclient/signing.go
> +	}
specs.Data as well

2024-03-12 10:13 UTC, olegshmuelov commented on beacon/goclient/signing.go
> +	}
```suggestion
tmp, exists := specs.Data["CAPELLA_FORK_VERSION"]
	if !exists {
		return phase0.Domain{}, fmt.Errorf("capella fork version not known by chain")
	}

	forkVersion, isForkVersion := tmp.(phase0.Version)
	if !isForkVersion {
		return phase0.Domain{}, fmt.Errorf("could not obtain CAPELLA_FORK_VERSION")
	}
```

2024-03-12 10:18 UTC, olegshmuelov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to obtain fork schedule")
IIRC we decide to not use errors package, but use fmt

2024-03-12 10:18 UTC, olegshmuelov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to obtain genesis")
IIRC we decide to not use errors package, but use fmt

2024-03-12 10:19 UTC, olegshmuelov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.New("failed to obtain genesis")
IIRC we decide to not use errors package, but use fmt

2024-03-12 10:19 UTC, olegshmuelov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to calculate signature domain")
IIRC we decide to not use errors package, but use fmt

2024-03-12 13:06 UTC, moshe-blox submitted a review, later dismissed

2024-03-12 13:14 UTC, nkryuchkov submitted a review, later dismissed
LGTM. No major requests, just minor nitpicks, hence approving

2024-03-12 13:14 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to obtain specs")
If we use `fmt.Errorf`, I think we should use it in all cases

2024-03-12 13:14 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, fmt.Errorf("failed to obtain specs")
Perhaps a bit different text would help to understand what exactly is nil if this error appears in logs

2024-03-12 13:14 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to obtain genesis")
fmt.Errorf

2024-03-12 13:14 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to calculate signature domain")
fmt

2024-03-12 13:14 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +	copy(domain[4:], root[:])
nit: I don't think we'll ever change domain length but perhaps we could make its length abstract, but I don't mind leaving it as it is
```suggestion
	copy(domain[len(spectypes.DomainVoluntaryExit):], root[:])
```

2024-03-12 13:14 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, fmt.Errorf("failed to obtain genesis")
I'd consider changing the text

2024-03-12 13:14 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +	"github.com/attestantio/go-eth2-client/api"
nit: I think this should be near "github.com/attestantio/go-eth2-client/spec/phase0" to be able to quickly see the scope of all imports from the library

2024-03-12 13:28 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +	copy(domain[4:], root[:])
Also, I just want to confirm something:

`phase0.Domain`' length is 32, spectypes.DomainVoluntaryExit is 4 and root is 32, so last 4 bytes of `root` won't be copied, but as I understand it's ok?

2024-03-12 13:40 UTC, olegshmuelov approved these changes

2024-03-12 13:42 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to calculate signature domain")
Still using errors

2024-03-12 13:42 UTC, nkryuchkov commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to calculate signature domain")
@olegshmuelov

2024-03-12 13:46 UTC, nkryuchkov approved these changes

2024-03-12 13:48 UTC, olegshmuelov approved these changes

2024-03-12 13:49 UTC, y0sher commented on beacon/goclient/signing.go
> +		return phase0.Domain{}, errors.Wrap(err, "failed to calculate signature domain")
I fixed it

2024-03-12 13:54 UTC, nkryuchkov approved these changes

2024-03-12 13:57 UTC, merged