Metrics Infrastructure
bloxapp/ssv pull request #169
Opened 2021-07-07 06:59 UTC by amir-blox

Resolve https://github.com/bloxapp/ssv/issues/159

2021-07-07 08:45 UTC, nivBlox requested changes

2021-07-07 08:45 UTC, nivBlox commented on cli/operator/node.go
> +			if err := metricsHandler.Start(http.NewServeMux(), ":15000"); err != nil {
lets add port to config

2021-07-07 08:45 UTC, nivBlox commented on metrics/collect.go
> +	prefix        = "ssv"
need to be distinct name - e.g "ssv-collect"

2021-07-08 15:35 UTC, lior-blox commented on cli/operator/node.go
> +	MetricsAPIAddr    string `yaml:"MetricsAPIAddr" env:"METRICS_API_ADDR" env-default:":15000" env-description:"address of metrics api"`
@amir-blox lets change it to MetricsPort

2021-07-08 15:36 UTC, lior-blox commented on cli/operator/node.go
> +	Metrics           string `yaml:"Metrics" env:"METRICS" env-default:"" env-description:"comma seperated list of metrics collectors"`
@amir-blox empty means all?

2021-07-08 15:37 UTC, lior-blox commented on cli/operator/node.go
> +		go startMetricsHandler(Logger, cfg)
@amir-blox lets add a way to disable metrics, could be that if port is not provided(default ) don't collect metrics

2021-07-11 17:12 UTC, merged