chore: remove prefork discovery
bloxapp/ssv pull request #1953
Opened 2024-12-18 16:33 UTC by y0sher

### Description 

This PR removes the dual discovery mechanism and leaves only the "post fork" discovery (with Protocol ID).

2025-01-27 17:40 UTC, iurii-ssv submitted a review, later dismissed
LGTM (if it tests fine on stage / QA)

2025-03-01 19:11 UTC, kchojn submitted a review, later dismissed

2025-03-12 01:10 UTC, nkryuchkov requested changes

2025-03-12 01:10 UTC, nkryuchkov commented on network/discovery/dv5_service.go
> +	dvs.bootnodes = dv5Cfg.Bootnodes // Just take bootnodes from one of the config since they're equal
The comment looks outdated, we have only one config

2025-03-12 01:10 UTC, nkryuchkov commented on network/discovery/service_test.go
> +	t.Run("Listener Type", func(t *testing.T) {
We don't need to keep it inside a subtest as it's just one case. Also, the test name is a bit misleading because we don't have different listener types anymore

2025-03-12 01:10 UTC, nkryuchkov commented on network/discovery/util_test.go
> +func TestingNetworkConfig() networkconfig.NetworkConfig {
The comment still mentions one of the old names

2025-07-18 00:37 UTC, nkryuchkov approved these changes

2025-07-18 05:01 UTC, kchojn approved these changes

2025-07-18 07:34 UTC, iurii-ssv approved these changes

2025-07-18 10:49 UTC, MatusKysel approved these changes
nice, I always like if we have less lines of the code :)

2025-07-18 10:50 UTC, MatusKysel commented
@y0sher `Commits must have verified signatures.` :(

2025-07-18 11:20 UTC, y0sher commented
@MatusKysel 
I wouldn't merge this PR without heavy testing anyway since we don't want to mess to with discovery. This is an old PR I did and we didn't merge it for a reason. Someone need to take on the pr and the most critical part and making sure there's no degradation in connectivity, number of peers, number of discovered peers, tec..

2025-07-18 13:23 UTC, nkryuchkov commented
Blocked for merging until tested well enough

2026-04-20 02:15 UTC, closed without merging