Contract v3 integration
bloxapp/ssv pull request #778
Opened 2022-12-22 17:53 UTC by olegshmuelov

2023-01-01 08:31 UTC, lior-blox requested changes

2023-01-01 08:31 UTC, lior-blox commented on cli/operator/node.go
>  	forksprotocol "github.com/bloxapp/ssv/protocol/forks"
@olegshmuelov Please check why tests are failing

2023-02-08 11:47 UTC, lior-blox commented
@olegshmuelov lets include this issue in this pr, please
#573

2023-03-08 13:11 UTC, olegshmuelov commented on operator/validator/event_handler.go
> +	}
should not be removed

2023-03-08 13:54 UTC, moshe-blox approved these changes

2023-03-08 13:54 UTC, lior-blox approved these changes

2023-03-08 13:55 UTC, merged