Spectest tests.json by module version
bloxapp/ssv pull request #781
Opened 2022-12-29 16:17 UTC by olegshmuelov

2023-01-01 11:18 UTC, lior-blox requested changes

2023-01-01 11:18 UTC, lior-blox commented on protocol/v2/qbft/spectest/qbft_mapping_test.go
>  	"strings"
@olegshmuelov Tests are failing

2023-01-01 12:09 UTC, nivBlox requested changes

2023-01-01 12:09 UTC, nivBlox commented on protocol/v2/testing/test_utils.go
> +func GetSpecTestJSON(path string, module string) ([]byte, error) {
lets make sure we overide the json file every time we run the test

2023-01-02 08:36 UTC, amir-blox commented on protocol/v2/testing/test_utils.go
> +	resp, err := http.Get(fmt.Sprintf("https://raw.githubusercontent.com/bloxapp/ssv-spec/%s/%s/spectest/generate/tests.json", version, module))
Downloading the json during test might make it unstable, why not downloading it in a dedicated make cmd?

2023-01-26 09:41 UTC, amir-blox approved these changes

2023-01-26 09:43 UTC, merged