SSZ
bloxapp/ssv pull request #878
Opened 2023-03-07 09:44 UTC by moshe-blox

2023-03-13 14:49 UTC, aaron-blox approved these changes

2023-03-14 09:21 UTC, lior-blox requested changes

2023-03-14 09:21 UTC, lior-blox commented on protocol/v2/ssv/validator/non_committee_validator.go
> -		if signedMsg == nil || signedMsg.Message == nil {
@moshe-blox why we added this check? what is the case to get nil msg?

2023-03-14 11:05 UTC, lior-blox approved these changes

2023-03-14 11:06 UTC, merged