Stage mainnet setup ci cd
bloxapp/ssv pull request #985
Opened 2023-06-05 09:46 UTC by systemblox

2023-06-05 12:07 UTC, olegshmuelov commented on .gitlab-ci.yml
>      # |  Deploy SSV nodes  |
Change to Deploy SSV Prater nodes

2023-06-05 12:17 UTC, olegshmuelov requested changes

2023-06-05 12:17 UTC, olegshmuelov commented on .gitlab-ci.yml
>      # │  Deploy Bootnode  |
change to Deploy Prater Bootnode

2023-06-05 12:17 UTC, olegshmuelov commented on .gitlab-ci.yml
> +    # +---------------------------+
Please add the same for Prater explorer

2023-06-05 12:17 UTC, olegshmuelov commented on .k8/production/mainnet/ssv-exporter-1.yml
> +            value: "true"
should be removed

2023-06-05 12:17 UTC, olegshmuelov commented on .k8/production/mainnet/ssv-exporter-2.yml
> +            value: "true"
should be removed

2023-06-05 13:15 UTC, systemblox commented on .gitlab-ci.yml
>      # |  Deploy SSV nodes  |
done

2023-06-05 13:37 UTC, systemblox commented on .k8/production/mainnet/ssv-exporter-1.yml
> +            value: "true"
done

2023-06-05 13:38 UTC, systemblox commented on .gitlab-ci.yml
>      # │  Deploy Bootnode  |
done

2023-06-06 13:09 UTC, olegshmuelov approved these changes

2023-06-08 08:29 UTC, moshe-blox approved these changes

2023-06-08 08:29 UTC, lior-blox commented on .gitlab-ci.yml
> +    - .k8/production/mainnet/scripts/deploy-boot-nodes.sh $DOCKER_REPO_INFRA_PROD $CI_BUILD_REF ssv $APP_REPLICAS_INFRA_PROD blox-infra-prod kubernetes-admin@blox-infra-prod ssv.network $K8S_API_VERS
@moshe-blox @systemblox this should be commented

2023-06-08 08:30 UTC, lior-blox commented on networkconfig/mainnet.go
> +	WhitelistedOperatorKeys: []string{
@moshe-blox please add a comment that these are blox exporters in all configs

2023-06-08 08:48 UTC, merged